New timer architecture using BukkitScheduler
Aechylus/TurnManager pull request #18
Opened 2021-11-26 07:33 UTC by Aechylus

Implementation for issue #17

2021-12-04 17:17 UTC, Phobez requested changes

2021-12-04 17:17 UTC, Phobez commented on src/com/clancraft/turnmanager/turn/TurnTimer.java
> +                timerDurationMillis % TimeUnit.MINUTES.toMillis(NORMAL_INTERVAL_MINS),
This parameter is `delay - Delay in server ticks before executing first repeat` right? Why not just `TimeUnit.MINUTES.toMillis(NORMAL_INTERVAL_MINS)`?

2021-12-04 17:32 UTC, Aechylus commented on src/com/clancraft/turnmanager/turn/TurnTimer.java
> +                timerDurationMillis % TimeUnit.MINUTES.toMillis(NORMAL_INTERVAL_MINS),
That's so the timer runs on multiples of NORMAL_INTERVAL_MINS. Say you have 17 mins left. I want the first broadcast to be 2 mins in the future, saying "Timer has 15 mins left".

2021-12-04 17:33 UTC, Phobez commented on src/com/clancraft/turnmanager/turn/TurnTimer.java
> +                timerDurationMillis % TimeUnit.MINUTES.toMillis(NORMAL_INTERVAL_MINS),
Ah, I see. Got it then

2021-12-04 17:33 UTC, Aechylus commented on src/com/clancraft/turnmanager/turn/TurnTimer.java
> +                timerDurationMillis % TimeUnit.MINUTES.toMillis(NORMAL_INTERVAL_MINS),
But anyways do you think it's a good idea to immediately broadcast timer on resumption with whatever values it has? Like a one-time "Timer has 17 mins left" and subsequently just the multiples of 5 mins?

2021-12-04 17:33 UTC, Phobez approved these changes

2021-12-04 17:34 UTC, Phobez commented on src/com/clancraft/turnmanager/turn/TurnTimer.java
> +                timerDurationMillis % TimeUnit.MINUTES.toMillis(NORMAL_INTERVAL_MINS),
Yeah I think that sounds fine. Are you going to add it to this PR as well?

2021-12-04 17:35 UTC, Aechylus commented on src/com/clancraft/turnmanager/turn/TurnTimer.java
> +                timerDurationMillis % TimeUnit.MINUTES.toMillis(NORMAL_INTERVAL_MINS),
I think so, and I'll add comments explaining what I did above too

2021-12-04 17:35 UTC, Phobez commented on src/com/clancraft/turnmanager/turn/TurnTimer.java
> +                timerDurationMillis % TimeUnit.MINUTES.toMillis(NORMAL_INTERVAL_MINS),
Alright then I'll hold off on merging

2021-12-04 18:30 UTC, Aechylus commented
Change is more extensive than I thought, but alas should be good now.

2021-12-13 13:29 UTC, Phobez approved these changes

2021-12-13 13:29 UTC, merged